<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
        <updateRate>100.0</updateRate>
        <robotNamespace>/</robotNamespace>
        <leftFrontJoint>wheel_FL_joint</leftFrontJoint>
        <rightFrontJoint>wheel_FR_joint</rightFrontJoint>
        <leftRearJoint>wheel_RL_joint</leftRearJoint>
        <rightRearJoint>wheel_RR_joint</rightRearJoint>
        <wheelSeparation>${chassis_length - 2*wheel_radius}</wheelSeparation>
        <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
        <robotBaseFrame>chassis</robotBaseFrame>
        <torque>20</torque>
        <topicName>cmd_vel</topicName>
        <broadcastTF>false</broadcastTF>
    </plugin>
    </gazebo>

</robot>
